In [36]:
#(a)
# for first condition
# |f(xk)| < Ea

def newton(f,D_f,x0,epsilon,iteration):
    
    xn = x0
    for n in range(0,iteration):
        fxk = f(xn)
        if abs(fxk) < epsilon:
            print('Found solution after',n,'iterations.\n')
            return xn
        D_fxk = D_f(xn)
        if D_fxk == 0:
            print('No root for zero derivative.')
            return None
        xn = xn - fxk/D_fxk
    print('Exceeded maximum number of iterations. No solution found.')
    return None

e = 2.71
Fun = lambda x: e**-x - 10**-9
Der_Of_Fun = lambda x: -e**-x
root = newton(Fun,Der_Of_Fun,0,0.001,100)
print('The root of given f(x) is:',root)

Found solution after 7 iterations.

The root of given f(x) is: 6.999999372831715


In [37]:
#(a)
# for second condition
# |f(xk)| < Er |f(x0)| + Ea

def newton(f,D_f,x0,epsilon,iteration):
    
    xn = x0
    for n in range(0,iteration):
        fxk = f(xn)
        z = (0.0000000001 * abs(fxk)) + 0.001
        if abs(fxk) < z:
            print('Found solution after',n,'iterations.\n')
            return xn
        D_fxk = D_f(xn)
        if D_fxk == 0:
            print('Zero derivative. No solution found.')
            return None
        xn = xn - fxk/D_fxk
    print('Exceeded maximum iterations. No solution found.')
    return None

e = 2.71
Fun = lambda x: e**-x - 10**-9
Der_Of_Fun = lambda x: -e**-x
root = newton(Fun,Der_Of_Fun,0,0.001,100)
print('The root of given f(x) is:',root)

Found solution after 7 iterations.

The root of given f(x) is: 6.999999372831715


In [38]:
#(a)
# for third condition
# |xk+1 - xk)| < Ea

def newton(f,D_f,x0,epsilon,iteration):
    
    xn = x0
    fxk = f(xn)
    D_fxk = D_f(xn)
    xnk = xn - fxk/D_fxk
    for n in range(0,iteration):
        
        fxk = f(xn)
        if abs(xnk - xn) < 0.001:
            print('Found solution after',n,'iterations.\n')
            return xn
        D_fxk = D_f(xn)
        if D_fxk == 0:
            print('Zero derivative. No solution found.')
            return None
        xn = xnk
        xnk = xn - fxk/D_fxk
    print('Exceeded maximum iterations. No solution found.')
    return None

e = 2.71
Fun = lambda x: e**-x - 10**-9
Der_Of_Fun = lambda x: -e**-x
root = newton(Fun,Der_Of_Fun,0,0.001,1000)
print('The root of given f(x) is:',root)

Found solution after 402 iterations.

The root of given f(x) is: 20.872548080185574


In [39]:
# (a)
# for fourth condition
# |(xk+1 - xk)| < Er |f(x0)| + Ea

def newton(f,D_f,x0,epsilon,iteration):
    
    xn = x0
    fxk = f(xn)
    D_fxk = D_f(xn)
    xnk = xn - fxk/D_fxk
    for n in range(0,iteration):
        
        fxk = f(xn)
        z = (0.0000000001 * abs(fxk)) + 0.001
        if abs(xnk - xn) < z:
            print('Found solution after',n,'iterations.\n')
            return xn
        D_fxk = D_f(xn)
        if D_fxk == 0:
            print('Zero derivative. No solution found.')
            return None
        xn = xnk
        xnk = xn - fxk/D_fxk
    print('Exceeded maximum iterations. No solution found.')
    return None

e = 2.71
Fun = lambda x: e**-x - 10**-9
Der_Of_Fun = lambda x: -e**-x
root = newton(Fun,Der_Of_Fun,0,0.001,1000)
print('The root of given f(x) is:',root)

Found solution after 402 iterations.

The root of given f(x) is: 20.872548080185574


In [40]:
#(b)
#find extremum point of given function

In [45]:
#(b)

# first condition ||Xk+1 - Xk|| < 0.0001

from sympy import symbols
import numpy as np

x,y = symbols('x y') #here we take x1=x and x2=y

fun = (x-1)**4 + (2*(x-1)**2)*((y-1)**2) + ((y+1)**4) - (2*(y-1)**2) - (2*y+1)**2 +1
x0 = np.array([[1.21,-1.15]])
e = 0.001
iteration = 100

df_x = fun.diff(x)
df_y = fun.diff(y)
df_xx = fun.diff(x,x)
df_yy = fun.diff(y,y)
df_xy = fun.diff(x,y)   
df_yx = fun.diff(y,x)

def newton(x0,e,iteration):
    counter = 1
    flag = 1
    stopping_criteria = True
    
    while stopping_criteria:
        gradient = np.array([df_x.subs({x:x0[0][0],y:x0[0][1]}).evalf(),
                     df_y.subs({x:x0[0][0],y:x0[0][1]}).evalf()])
        
        hessian = np.matrix([[df_xx.subs({x:x0[0][0],y:x0[0][1]}).evalf(),df_yx.subs({x:x0[0][0],y:x0[0][1]}).evalf()],
                        [df_xy.subs({x:x0[0][0],y:x0[0][1]}).evalf(),df_yy.subs({x:x0[0][0],y:x0[0][1]}).evalf()]],dtype=float)
        
        x1 = np.array(x0 - np.array(np.dot(gradient,np.linalg.inv(hessian))),dtype=float)
        print('Iteration: ',counter)
        counter = counter +1
        
        if counter > iteration:
            flag = 0
            break
            
        print(x0,x1)
        stopping_criteria = np.linalg.norm(x1-x0) > e
        x0=x1
        
    if flag == 1:
        print('\n\n\nExtremum point for given f(x) is: ',x0)
    else:
        print('\nNot found any extremum point within given iteration.')
        
newton(x0,e,iteration)

Iteration:  1
[[ 1.21 -1.15]] [[1.22347794 0.0062247 ]]
Iteration:  2
[[1.22347794 0.0062247 ]] [[ 5.74413364 12.10449565]]
Iteration:  3
[[ 5.74413364 12.10449565]] [[4.53149904 7.73513692]]
Iteration:  4
[[4.53149904 7.73513692]] [[3.72503909 4.84502883]]
Iteration:  5
[[3.72503909 4.84502883]] [[3.15949736 2.95707653]]
Iteration:  6
[[3.15949736 2.95707653]] [[2.69901629 1.75793293]]
Iteration:  7
[[2.69901629 1.75793293]] [[2.26836071 1.01879421]]
Iteration:  8
[[2.26836071 1.01879421]] [[1.85023558 0.54058313]]
Iteration:  9
[[1.85023558 0.54058313]] [[1.37603724 0.11254893]]
Iteration:  10
[[1.37603724 0.11254893]] [[-0.16325096 -2.15878114]]
Iteration:  11
[[-0.16325096 -2.15878114]] [[-1.91947523  2.98941097]]
Iteration:  12
[[-1.91947523  2.98941097]] [[-1.14706992  1.81596466]]
Iteration:  13
[[-1.14706992  1.81596466]] [[-0.54191668  1.086685  ]]
Iteration:  14
[[-0.54191668  1.086685  ]] [[-0.04461626  0.61249457]]
Iteration:  15
[[-0.04461626  0.61249457]] [[0.42701068 0.2

In [49]:
#(b)

# second condition ||Xk+1 - Xk|| < Er||D(Fx0)|| + 0.0001

from sympy import symbols
import numpy as np

x,y = symbols('x y') #here we take x1=x and x2=y

fun = (x-1)**4 + (2*(x-1)**2)*((y-1)**2) + ((y+1)**4) - (2*(y-1)**2) - (2*y+1)**2 +1
x0 = np.array([[1.21,-1.15]])



df_x = fun.diff(x)
df_y = fun.diff(y)
df_xx = fun.diff(x,x)
df_yy = fun.diff(y,y)
df_xy = fun.diff(x,y)   
df_yx = fun.diff(y,x)

#Calculating value of e according to given condition

l = np.array([df_x.subs({x:x0[0][0],y:x0[0][1]}).evalf(),df_y.subs({x:x0[0][0],y:x0[0][1]}).evalf()],dtype=float)
norm_of_fun = np.linalg.norm(l)
e = 10**(-4)*norm_of_fun + 10**(-4)
print(e)
iteration = 100


#creating function to find extremum point using above value of e

def newton(x0,e,iteration):
    counter = 1
    flag = 1
    stopping_criteria = True
    
    while stopping_criteria:
        gradient = np.array([df_x.subs({x:x0[0][0],y:x0[0][1]}).evalf(),
                     df_y.subs({x:x0[0][0],y:x0[0][1]}).evalf()])
        
        hessian = np.matrix([[df_xx.subs({x:x0[0][0],y:x0[0][1]}).evalf(),df_yx.subs({x:x0[0][0],y:x0[0][1]}).evalf()],
                        [df_xy.subs({x:x0[0][0],y:x0[0][1]}).evalf(),df_yy.subs({x:x0[0][0],y:x0[0][1]}).evalf()]],dtype=float)
        
        x1 = np.array(x0 - np.array(np.dot(gradient,np.linalg.inv(hessian))),dtype=float)
        print('Iteration: ',counter)
        counter = counter +1
        
        if counter > iteration:
            flag = 0
            break
            
        print(x0,x1)
        stopping_criteria = np.linalg.norm(x1-x0) > e
        x0=x1
        
    if flag == 1:
        print('\n\n\nExtremum point for given f(x) is: ',x0)
    else:
        print('\nNot found any extremum within given iteration.')
        
newton(x0,e,iteration)

0.001496853769657855
Iteration:  1
[[ 1.21 -1.15]] [[1.22347794 0.0062247 ]]
Iteration:  2
[[1.22347794 0.0062247 ]] [[ 5.74413364 12.10449565]]
Iteration:  3
[[ 5.74413364 12.10449565]] [[4.53149904 7.73513692]]
Iteration:  4
[[4.53149904 7.73513692]] [[3.72503909 4.84502883]]
Iteration:  5
[[3.72503909 4.84502883]] [[3.15949736 2.95707653]]
Iteration:  6
[[3.15949736 2.95707653]] [[2.69901629 1.75793293]]
Iteration:  7
[[2.69901629 1.75793293]] [[2.26836071 1.01879421]]
Iteration:  8
[[2.26836071 1.01879421]] [[1.85023558 0.54058313]]
Iteration:  9
[[1.85023558 0.54058313]] [[1.37603724 0.11254893]]
Iteration:  10
[[1.37603724 0.11254893]] [[-0.16325096 -2.15878114]]
Iteration:  11
[[-0.16325096 -2.15878114]] [[-1.91947523  2.98941097]]
Iteration:  12
[[-1.91947523  2.98941097]] [[-1.14706992  1.81596466]]
Iteration:  13
[[-1.14706992  1.81596466]] [[-0.54191668  1.086685  ]]
Iteration:  14
[[-0.54191668  1.086685  ]] [[-0.04461626  0.61249457]]
Iteration:  15
[[-0.04461626  0.612494